### ISSUE TITLE
Episode 

### ISSUE THREAD

**Issue by 48klocs** [Butlins12/destiny-rolls#11]
https://github.com/48klocs/dim-wish-list-sources/issues/199 is an open issue for https://github.com/Adamsdown-Boy/destiny-rolls/blob/main/player-versus-enemies-rolls/ep108-final-shape-world-weapons.txt

**Comment by Adamsdown-Boy** [comment]
Oh arse! My QA for this file was not good, was it? Give me a sec...

**Comment by Adamsdown-Boy** [comment]
Okay, changes made. Everything should now read episode 108 in the descriptions now!
