### ISSUE TITLE
Solipsism god roll mistake

### ISSUE THREAD

**Issue by J-Wo** [Butlins12/destiny-rolls#12]
Your recommendation for Stag-Harmony doesn't make sense. You're saying that you can build your super back with Harmony, but that Stag will give increased resistance to allies in a well. Problem is Well isn't on prismatic, and Solipsism only works on prismatic subclass

**Comment by Adamsdown-Boy** [comment]
You are quite right! I'll get DIM to pull it. Thanks for pointing it out.

**Comment by Adamsdown-Boy** [comment]
Reported to DIM and removed from voltron.txt
