### ISSUE TITLE
Consolidated List Of All Rolls?

### ISSUE THREAD

**Issue by myn** [Butlins12/destiny-rolls#8]
Love what you are doing here.  A ton of work going into these and I believe your current rolls reflect the communities position on best rolls.

Was wondering if you had a consolidated list of all your roles that we can incorporate into DIM?

**Comment by Adamsdown-Boy** [comment]
Thanks for the compliment - they should already be in there! The files you see here are the ones I use for proofing and correcting before I send the link to 48klocs for incorporation into the main voltron.txt file. So everything should be in DIM a few days after appearing here.

**Comment by myn** [comment]
Excellent!  Appreciate this answer and all the work you do!
