### ISSUE TITLE
Double commas on various wishlist rolls

### ISSUE THREAD

**Issue by whyayala** [Butlins12/destiny-rolls#9]
Sup, thanks for your work transcribing DMB and PVE to wishlists for the voltron. 

Some context. I parse the voltron semi regularly to filter out rolls I don't want, sort the ones I want by tags, then spit them out into a new file. I noticed that my outputted file was very small on the last run. When this happens, it usually is because something changed on the voltron that my parser wasn't expecting. 

When I inspected it more closely, I found that some rolls for the taken weapons this season had double commas in them. I'm not sure if this was intentional or a side effect of some tool you were using that generates the wishlists, but I wanted to call it to your attention. At a quick glance it looks like the rolls with double commas aren't getting listed in dim either. For example, there is a grouping of 16 rolls for rapacious appetite with perp motion and headstone, where 4 of which have extra commas, and in dim when I check the possible wishlist rolls I only see 12 for perp motion and headstone.

Here's one instance from your wishlist file. 
https://github.com/Adamsdown-Boy/destiny-rolls/blob/10dfd51b9c54ecb19dfec28e6ac2ee811723a6d0/player-versus-enemies-rolls/ep66-taken-and-reckoning-weapons.txt#L20C46-L20C46

If you'd like, I can just fix them by hand and open a pr. LMK, I'm in the discord and on github.

**Comment by Adamsdown-Boy** [comment]
Yeah, I'm using 48klocs wishlist tool (https://48klocs.github.io/wish-list-magic-wand/fingerwave.html), so it's a fairly manual process. I've got all the files saved as text files, so it's probably as easy to use Notepad++ to find and replace, as I'll need to tell him which lines he needs to swap out in the voltron.txt file.

Thanks for letting me know though - it's another QA step I'll add in when I'm finished with a roll list!

**Comment by Adamsdown-Boy** [comment]
Three files to sort! DMB298, and PvE44 and 66. Not as bad as it could be, I suppose...

**Comment by Adamsdown-Boy** [comment]
Done - 48klocs should roll it out with the next update.

**Comment by whyayala** [comment]
@Adamsdown-Boy  Thanks chief. Happy 4th of July.
